version: '3.8'

services:
  image-uploader:
    build: .
    container_name: image-uploader
    ports:
      - "3200:3200"
    environment:
      - NODE_ENV=production
      - PORT=3200
    volumes:
      - ./uploads:/app/uploads        # ✅ Now persistent
      - ./public:/app/public
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
